# Generated by Django 2.2.12 on 2021-03-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Producto')),
            ],
            options={
                'verbose_name': ('Producto',),
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
