# Generated by Django 2.2.12 on 2021-03-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=1, max_length=30, verbose_name='Código de barras'),
            preserve_default=False,
        ),
    ]
