# Generated by Django 2.2.12 on 2021-03-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nombre',
            new_name='name',
        ),
    ]
